services:
  db:
    container_name: eshop_db
    image: mysql:8
    environment:
      - MYSQL_DATABASE=eshop
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3307:3306'
    volumes:
      - eshop_db_volume:/var/lib/mysql

volumes:
  eshop_db_volume:
